### ISSUE TITLE
Power ESP32 from NanoHub serial

### ISSUE THREAD

**Issue by dj-louw** [denvera/esp32-nanoview#1]
Hello

I'm not really sure how else to reach out to you other than creating an issue here.

I want to connect my NanoView to an ESP32 for probably the same reason you do.

The documentation on the NanoView website is very sparse and I want to know if it's possible to power the ESP from the serial connector's power pin?

How did you power your ESP? When I power mine from the NanoHub it does not seem to do anything other than the power LED dimming slightly every 500ms. When the ESP is powered by USB or something, then it is able to grab the serial data successfully.

Your insights and experiences into this will be greatly appreciated!

**Comment by denvera** [comment]
Hey there,

I did exactly what you did, and ended up with the same result sadly. Currently I just power mine from a USB charger, I didn't get anywhere trying to run it off the NanoView hub 5v line unfortunately.

Also if you're interested, I can share my Grafana dashboards and Telegraf configs if that'd help at all. Thanks for taking a look at the project!

**Comment by dj-louw** [comment]
Ah ok thanks for the info. My DB board is quite far away from any power socket, so I'll have to cobble something together that gets power straight from the db board or something.

I'm happy for you to share with me whatever you have that you are willing to share, thanks!

**Comment by dj-louw** [comment]
Just saw the updated project. Thank you so much! 🌮
